# Generated by Django 6.0.4 on 2026-04-25 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('project_type', models.CharField(choices=[('FILM', 'Film'), ('SERIES', 'Series'), ('YOUTUBE', 'YouTube'), ('CLIP', 'Music Clip'), ('SHORT_FILM', 'Short Film'), ('OTHER', 'Other')], default='YOUTUBE', max_length=30)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField()),
                ('synopsis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CASTING', 'Casting'), ('PRE_PRODUCTION', 'Pre-production'), ('PRODUCTION', 'Production'), ('POST_PRODUCTION', 'Post-production'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUCER', 'Producer'), ('DIRECTOR', 'Director'), ('SCRIPTWRITER', 'Scriptwriter'), ('ACTOR', 'Actor'), ('CAMERAMAN', 'Cameraman'), ('EDITOR', 'Editor'), ('CREW', 'Crew')], default='ACTOR', max_length=30)),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('character_description', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
