# Generated by Django 6.0.4 on 2026-04-24 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('acting_experience', models.BooleanField(default=False)),
                ('experience_details', models.TextField(blank=True)),
                ('portfolio_link', models.URLField(blank=True)),
                ('languages', models.CharField(max_length=255)),
                ('special_skills', models.TextField(blank=True)),
                ('camera_confidence', models.PositiveSmallIntegerField()),
                ('available_for_filming', models.BooleanField(default=False)),
                ('available_for_rehearsals', models.BooleanField(default=False)),
                ('motivation', models.TextField()),
                ('reliability_reason', models.TextField()),
                ('preferred_role', models.CharField(choices=[('LEAD', 'Lead'), ('SUPPORTING', 'Supporting'), ('EXTRA', 'Extra')], default='SUPPORTING', max_length=30)),
                ('role_limitations', models.TextField(blank=True)),
                ('headshot', models.ImageField(upload_to='applications/headshots/')),
                ('video', models.FileField(upload_to='applications/videos/')),
                ('commitment_confirmed', models.BooleanField(default=False)),
                ('signed_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('NEEDS_MORE_INFO', 'Needs more info')], default='PENDING', max_length=30)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='castings.casting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
