# Generated by Django 6.0.4 on 2026-04-26 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('PROJECT', 'Project'), ('FILE', 'File'), ('SCHEDULE', 'Schedule'), ('LOCATION', 'Location'), ('CASTING', 'Casting'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('related_project_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
